// src/lib/products.ts
export const products = [
  {
    name: 'Golden Nectar',
    slug: 'golden-nectar',
    description: 'A sweet and floral mead with hints of honey and citrus. This mead represents the warmth of a summer evening.',
    image: 'https://placehold.co/600x600/FACC15/000000/png?text=Golden+Nectar',
    details: {
      size: '750ml',
      price: '€25.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Clear, bright gold',
      taste: 'Sweet, honey, citrus',
      smell: 'Floral, honey',
      body: 'Medium-bodied',
      alcohol: '12%',
    },
    ingredients: ['Water', 'Honey', 'Yeast', 'Orange Peel', 'Spices'],
  },
  {
    name: 'Wildflower Brew',
    slug: 'wildflower-brew',
    description: 'A complex and aromatic mead with a blend of wildflower honey.',
    image: 'https://placehold.co/600x600/8B5CF6/FFFFFF/png?text=Wildflower+Brew',
    details: {
      size: '750ml',
      price: '€28.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Amber color',
      taste: 'Complex, floral, earthy',
      smell: 'Aromatic, wildflower honey',
      body: 'Full-bodied',
      alcohol: '13%',
    },
    ingredients: ['Water', 'Wildflower Honey', 'Yeast'],
  },
  {
    name: 'Spiced Mead',
    slug: 'spiced-mead',
    description: 'A warm and spicy mead with notes of cinnamon, cloves, and nutmeg.',
    image: 'https://placehold.co/600x600/F97316/FFFFFF/png?text=Spiced+Mead',
    details: {
      size: '750ml',
      price: '€27.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Deep amber',
      taste: 'Warm, spicy, sweet',
      smell: 'Cinnamon, cloves, nutmeg',
      body: 'Medium-bodied',
      alcohol: '12.5%',
    },
    ingredients: ['Water', 'Honey', 'Yeast', 'Cinnamon', 'Cloves', 'Nutmeg'],
  },
  {
    name: 'Forest Blend',
    slug: 'forest-blend',
    description: 'A rich and earthy mead with a deep, complex flavor profile.',
    image: 'https://placehold.co/600x600/16A34A/FFFFFF/png?text=Forest+Blend',
    details: {
      size: '750ml',
      price: '€30.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Dark brown',
      taste: 'Earthy, woody, complex',
      smell: 'Forest floor, oak',
      body: 'Full-bodied',
      alcohol: '14%',
    },
    ingredients: ['Water', 'Forest Honey', 'Yeast', 'Oak Chips'],
  },
  {
    name: 'Berry Burst',
    slug: 'berry-burst',
    description: 'A fruity mead with a mix of summer berries.',
    image: 'https://placehold.co/600x600/EC4899/FFFFFF/png?text=Berry+Burst',
    details: {
      size: '750ml',
      price: '€26.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Ruby red',
      taste: 'Sweet, tart, fruity',
      smell: 'Berries, honey',
      body: 'Light-bodied',
      alcohol: '11%',
    },
    ingredients: ['Water', 'Honey', 'Yeast', 'Mixed Berries'],
  },
  {
    name: 'Mountain Honey',
    slug: 'mountain-honey',
    description: 'A traditional mead made with honey from mountain flowers.',
    image: 'https://placehold.co/600x600/FBBF24/000000/png?text=Mountain+Honey',
    details: {
      size: '750ml',
      price: '€29.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Golden hue',
      taste: 'Pure, sweet, floral',
      smell: 'Mountain flowers, honey',
      body: 'Medium-bodied',
      alcohol: '12%',
    },
    ingredients: ['Water', 'Mountain Honey', 'Yeast'],
  },
  {
    name: 'Viking Blood',
    slug: 'viking-blood',
    description: 'A strong, bold mead with a hint of cherry.',
    image: 'https://placehold.co/600x600/DC2626/FFFFFF/png?text=Viking+Blood',
    details: {
      size: '750ml',
      price: '€32.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Deep red',
      taste: 'Strong, bold, cherry notes',
      smell: 'Cherry, honey, alcohol',
      body: 'Full-bodied',
      alcohol: '15%',
    },
    ingredients: ['Water', 'Honey', 'Yeast', 'Cherry Juice'],
  },
  {
    name: 'Druid\'s Draught',
    slug: 'druids-draught',
    description: 'A herbal mead with a secret blend of herbs and spices.',
    image: 'https://placehold.co/600x600/22C55E/FFFFFF/png?text=Druid%27s+Draught',
    details: {
      size: '750ml',
      price: '€31.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Greenish gold',
      taste: 'Herbal, complex, semi-sweet',
      smell: 'Herbs, spices, honey',
      body: 'Medium-bodied',
      alcohol: '13.5%',
    },
    ingredients: ['Water', 'Honey', 'Yeast', 'Secret Herbal Blend'],
  },
  {
    name: 'King\'s Mead',
    slug: 'kings-mead',
    description: 'A premium mead, aged in oak barrels for a rich, smooth taste.',
    image: 'https://placehold.co/600x600/D97706/FFFFFF/png?text=King%27s+Mead',
    details: {
      size: '750ml',
      price: '€40.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Rich gold',
      taste: 'Smooth, rich, oaky',
      smell: 'Oak, vanilla, honey',
      body: 'Full-bodied',
      alcohol: '14.5%',
    },
    ingredients: ['Water', 'Honey', 'Yeast', 'Aged in Oak Barrels'],
  },
  {
    name: 'Queen\'s Delight',
    slug: 'queens-delight',
    description: 'A light and refreshing mead with a hint of peach.',
    image: 'https://placehold.co/600x600/F472B6/FFFFFF/png?text=Queen%27s+Delight',
    details: {
      size: '750ml',
      price: '€27.00',
      availability: 'In Stock',
    },
    characteristics: {
      organoleptic: 'Pale gold',
      taste: 'Light, refreshing, peach notes',
      smell: 'Peach, honey, floral',
      body: 'Light-bodied',
      alcohol: '11.5%',
    },
    ingredients: ['Water', 'Honey', 'Yeast', 'Peach Flavor'],
  }
];
