

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "80:80"   # HTTP port for redirect to HTTPS
      - "443:443" # HTTPS port
    networks:
      - react-rust
    env_file:
      - .env
    volumes:
      - 'miedaria_paunilor_images:/app/images'
      - './ssl:/etc/nginx/ssl:ro'  # Mount SSL certificates 

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - react-rust
      - rust-postgres
    env_file:
      - .env
    volumes:
      - 'miedaria_paunilor_images:/app/images' 

  database:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    networks:
      - rust-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  react-rust:
  rust-postgres:

volumes:
  postgres-data:
  miedaria_paunilor_images: 
